FROM alpine:3.21

ARG TARGETOS
ARG TARGETARCH

RUN apk add --no-cache ca-certificates tzdata

COPY ${TARGETOS}_${TARGETARCH}/nookclaw /usr/local/bin/nookclaw
COPY docker/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
